import {EmployeeSubmitPayload} from "@/types/employee";

export const employee: EmployeeSubmitPayload = {
    nip_pegawai: '',
    nip_pns: '',
    gelar_depan: '',
    gelar_belakang: '',
    nama_pegawai: '',
    id_ms_negara_tinggal: 1,
    id_ms_provinsi_tinggal: '',
    id_ms_kota_tinggal: '',
    id_ms_kecamatan_tinggal: '',
    id_ms_desa_tinggal: '',
    alamat_tinggal: '',
    kode_pos_tinggal: '',
    rt_tinggal: '',
    rw_tinggal: '',
    tempat_lahir: '',
    id_jenis_kelamin: 1,
    id_ms_golongan_darah: 1,
    id_ms_status_kawin: 1,
    id_ms_agama: 1,
    hp: '',
    email: '',
    no_ktp: '',
    status_pns: 0,
    status_aktif: 1,
    tgl_lahir: '',
    tgl_masuk: '',
    tgl_keluar: '',
    foto: undefined,
    file_ktp: undefined,
    file_kk: undefined,
    file_ktam: undefined,
    file_npwp: undefined,
    id_ms_pendidikan: 0,
    id_ms_status_pegawai: 0,
    id_ms_spesialis: 0,
    id_pangkat: 0,
    id_jabatan: 0,
    kode_dpjp: '',
    id_ms_jenis_pegawai: 0,
    id_ms_unit_kerja: 1,
    id_ms_unit_induk: 1
}
