import {Employee} from "@/types/employee";

export const employee: Employee = {
    nip_pegawai: '',
    nip_pns: '',
    gelar_depan: '',
    gelar_belakang: '',
    nama_pegawai: '',
    id_ms_negara_tinggal: 1,
    id_ms_provinsi_tinggal: '',
    id_ms_kota_tinggal: '',
    id_ms_kecamatan_tinggal: '',
    id_ms_desa_tinggal: '',
    alamat_tinggal: '',
    kode_pos_tinggal: '',
    rt_tinggal: '',
    rw_tinggal: '',
    tempat_lahir: '',
    id_jenis_kelamin: 1,
    id_ms_golongan_darah: 1,
    id_ms_status_kawin: 1,
    id_ms_agama: 1,
    hp: '',
    email: '',
    no_ktp: '',
    foto: '',
    status_pns: 0,
    status_aktif: 0,
    tgl_lahir: new Date(),
    tgl_masuk: new Date(),
    tgl_keluar: new Date(),
    file_ktp: "",
    file_kk: "",
    file_ktam: "",
    file_npwp: "",
    id_pegawai: 1
}
