import {PatientType} from "@/types/patient";

export const patient: PatientType = {
    id_pasien: 1,
    kode_rm: "",
    nama_pasien: "",
    tempat_lahir: "",
    tgl_lahir: new Date(),
    jenis_kelamin: 1,
    id_warga_negara: 0,
    identitas_pasien: 0,
    no_identitas: "",
    no_bpjs: "",
    no_hp: "",
    id_ms_negara_tinggal: 0,
    id_ms_provinsi_tinggal: "",
    id_ms_kota_tinggal: "",
    id_ms_kecamatan_tinggal: "",
    id_ms_desa_tinggal: "",
    alamat_tinggal: "",
    rt_tinggal: "",
    rw_tinggal: "",
    alamatgab_tinggal: "",
    id_ms_agama: 0,
    rt_asal: "",
    rw_asal: "",
    id_ms_negara_asal: 0,
    id_ms_propinsi_asal: "",
    id_ms_kota_asal: "",
    id_ms_kecamatan_asal: "",
    id_ms_desa_asal: "",
    alamat_asal: "",
    alamatgab_asal: "",
    id_ms_pendidikan: 0,
    kode_pos_tinggal: "",
    kode_pos_asal: "",
    nama_ibu_kandung:"",
    nama_pekerjaan: ""
};
