export const registrationDefaultValue = {
    cob: null,
    no_cob: '',
    nama_wali: '',
    telp_wali: '',
    id_hub_wali: undefined,
    asal_rujukan: '',
    nama_perujuk: '',
    status_bpjs: 1,
    status_inap: 1,
    jenis_pasien: ' ',
    ket_rujukan: '',
    status_rujukan: '1',
    nomor_rujuk_balik: '',
    tgl_rujukan: ' ',
    tgl_daftar: ' ',
    id_asuransi: undefined,
    nomor_asuransi: ' ',
    no_rujukan: ' ',
};
