export const buildDefaultValue = (ppkPelayanan: string) => {
    return {
        noKartu: '',
        tglSep: new Date().toISOString().split('T')[0],
        jnsPelayanan: '',
        klsRawatHak: '',
        klsRawatNaik: '',
        ppkPelayanan: ppkPelayanan,
        pembiayaan: '',
        penanggungJawab: '',
        noMR: '',
        asalRujukan: '',
        tglRujukan: '',
        noRujukan: '',
        ppkRujukan: '',
        catatan: '',
        diagAwal: '',
        tujuan: '',
        eksekutif: '0',
        cob: '0',
        katarak: '0',
        lakaLantas: '0',
        noLP: '',
        tglKejadian: '',
        keterangan: '',
        suplesi: '',
        noSepSuplesi: '',
        kdPropinsi: '',
        kdKabupaten: '',
        kdKecamatan: '',
        tujuanKunj: '',
        flagProcedure: '',
        kdPenunjang: '',
        assesmentPel: '',
        kodeDPJP: '',
        dpjpLayan: '',
        noTelp: '',
        user: '',
    };
};
