enum Action {
    VIEW = 'VIEW',
    CREATE = 'CREATE',
    UPDATE_FIELDS = 'UPDATE_FIELDS',
    UPDATE_STATUS = 'UPDATE_STATUS',
    UPDATE_QUEUE_STATUS = 'UPDATE_QUEUE_STATUS',
    DELETE = 'DELETE'
}

export {Action}