export type SEP = {
    noKartu: string;
    tglSep: string;
    jnsPelayanan: string;
    klsRawatHak: string;
    klsRawatNaik: string;
    pembiayaan: string;
    penanggungJawab: string;
    noMR: string;
    asalRujukan: string;
    tglRujukan: string;
    noRujukan: string;
    ppkRujukan: string;
    catatan: string;
    diagAwal: string;
    tujuan: string;
    eksekutif: string;
    cob: string;
    katarak: string;
    lakaLantas: string;
    noLP?: string | null;
    tglKejadian?: string | null;
    keterangan?: string | null;
    noSepSuplesi?: string | null;
    kdPropinsi?: string | null;
    kdKabupaten?: string | null;
    kdKecamatan?: string | null;
    tujuanKunj: string;
    flagProcedure?: string | null;
    kdPenunjang?: string | null;
    kodeDPJP: string;
    dpjpLayan?: string | null;
    noTelp: string;
    user: string;
};
